### ISSUE TITLE
Allow docs.metadata.json as an alternative to docs.metadata

### ISSUE THREAD

**Issue by jskeet** [googleapis/docuploader#37] opened 2020-07-28 17:29 UTC
It can be useful to create docs metadata from code rather than via the docuploader command line. Currently docuploader uses a textproto file format - if you could pass in a JSON file as an alternative (which could then just be parsed to the same metadata - or even just a separate command line to convert from JSON to textproto) that would make life a lot simpler in some cases.

**Comment by tbpg** [comment] 2020-09-14 03:33
Duplicate of #11.

**Comment by jskeet** [comment] 2021-01-06 15:58
Reopening, as it's not quite the same thing as #11 - that's about .repo-metadata, which contains different things. This is about having *exactly* the same structure (https://github.com/googleapis/docuploader/blob/master/docuploader/protos/metadata.proto) - but allowing the content to be specified as JSON.

**Closed** 2021-01-26 20:38 UTC
Labels: type: feature request
